name: Auto-Healing Deployment Pipeline

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'apply'
        type: choice
        options:
          - plan
          - apply
          - destroy

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  terraform_plan:
    name: Terraform Plan
    uses: ./.github/workflows/terraform-reusable.yml
    with:
      action: plan
      working-directory: terraform
    secrets:
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    if: github.event.inputs.action == 'plan'

  terraform_apply:
    name: Terraform Apply
    uses: ./.github/workflows/terraform-reusable.yml
    with:
      action: apply
      working-directory: terraform
    secrets:
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    if: github.event.inputs.action == 'apply'

  terraform_destroy:
    name: Terraform Destroy
    uses: ./.github/workflows/terraform-reusable.yml
    with:
      action: destroy
      working-directory: terraform
    secrets:
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    if: github.event.inputs.action == 'destroy'

  capture_job_id:
    name: Capture Job Names and IDs, Fetch Logs
    runs-on: ubuntu-latest
    needs: [terraform_plan, terraform_apply, terraform_destroy]  # Runs after all jobs
    if: failure()  # Ensures execution even if previous jobs fail
    steps:
      - name: Get Workflow Run Jobs (Names and IDs)
        run: |
          JOB_DETAILS=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs --jq '.jobs[] | "\(.id) \(.name)"')
          
          echo "JOB_DETAILS<<EOF" >> $GITHUB_ENV
          echo "$JOB_DETAILS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

          echo "Captured Job Details:"
          echo "$JOB_DETAILS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug Job Details
        run: |
          echo "Job Details Retrieved:"
          echo "$JOB_DETAILS"

      - name: Fetch Logs for All Jobs
        run: |
          while IFS= read -r line; do
            JOB_ID=$(echo $line | awk '{print $1}')
            JOB_NAME=$(echo $line | awk '{print substr($0, index($0,$2))}')
            echo "Fetching logs for Job ID: $JOB_ID, Job Name: $JOB_NAME"
            gh api repos/${{ github.repository }}/actions/jobs/${JOB_ID}/logs
          done <<< "$JOB_DETAILS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

