name: Deploy to Azure Container Apps

on:
  workflow_dispatch:

permissions:
      id-token: write
      contents: read

jobs:
  aicicd:
    name: aicicd-poc
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        id: login
        uses: azure/login@v1
        with:
         client-id: ${{ secrets.AZURE_CLIENT_ID }}
         tenant-id: ${{ secrets.AZURE_TENANT_ID }}
         subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
         
      - name: Capture Output
        run: |
          echo "Terraform Output:" > output.log
          cat $GITHUB_WORKSPACE | tee -a output.log
          
      - name: Upload Output File
        uses: actions/upload-artifact@v4
        with:
          name: terraform-output
          path: output.log
  
