name: Auto-Healing Deployment Pipeline

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'apply'
        type: choice
        options:
          - plan
          - apply
          - destroy

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  terraform_plan:
    name: Terraform Plan
    uses: ./.github/workflows/terraform-reusable.yml
    with:
      action: plan
      working-directory: terraform
    secrets:
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    if: github.event.inputs.action == 'plan'

  terraform_apply:
    name: Terraform Apply
    uses: ./.github/workflows/terraform-reusable.yml
    with:
      action: apply
      working-directory: terraform
    secrets:
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    if: github.event.inputs.action == 'apply'

  terraform_destroy:
    name: Terraform Destroy
    uses: ./.github/workflows/terraform-reusable.yml
    with:
      action: destroy
      working-directory: terraform
    secrets:
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    if: github.event.inputs.action == 'destroy'

  capture_job_id:
    name: Capture aicicd Job ID on Failure
    runs-on: ubuntu-latest
    needs: [terraform_plan, terraform_apply, terraform_destroy]
    if: always() # Runs only if aicicd fails
    steps:
      - name: Get Workflow Run Jobs
        run: |
          JOBS=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs --jq '.jobs[] | .id')
          echo "JOB_IDS=$JOBS" >> $GITHUB_ENV
          echo "Captured Job IDs: $JOBS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug Job ID
        run: |
          echo "Job IDs retrieved: $JOB_IDS"

      - name: Fetch Logs for All Jobs
        run: |
          for JOB_ID in $JOB_IDS; do
            echo "Fetching logs for Job ID: $JOB_ID"
            gh api repos/${{ github.repository }}/actions/jobs/$JOB_ID/logs
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}