name: Deploy to Azure Container Apps

on:
  workflow_dispatch:

permissions:
      id-token: write
      contents: read

jobs:
  aicicd:
    name: aicicd-poc
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
         client-id: ${{ secrets.AZURE_CLIENT_ID }}
         tenant-id: ${{ secrets.AZURE_TENANT_ID }}
         subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  capture_logs:
    name: Capture Logs
    needs: [aicicd]
    runs-on: ubuntu-latest
    steps:
      - name: Fetch AICICD Logs
        run: |
          mkdir -p logs
          gh run view ${{ github.run_id }} --log > logs/aicicd_error_log.txt || echo "Error log capture failed."

      - name: Print Logs Before Uploading
        run: |
          echo "========== START OF AICICD ERROR LOG =========="
          cat logs/aicicd_error_log.txt || echo "Error log is empty."
          echo "=========== END OF AICICD ERROR LOG ==========="
