name: Deploy to Azure Container Apps

on:
  workflow_dispatch:

permissions:
      id-token: write
      contents: read

jobs:
  aicicd:
    name: aicicd-poc
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
         client-id: ${{ secrets.AZURE_CLIENT_ID }}
         tenant-id: ${{ secrets.AZURE_TENANT_ID }}
         subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  capture_logs:
    name: Capture Logs
    needs: [aicicd]
    runs-on: ubuntu-latest
    steps:
      - name: Fetch and Save Job Logs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p logs
          echo "Fetching logs for aicicd job..."

          # Get the workflow run ID
          RUN_ID=$(curl -s -H "Authorization: token $GH_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs?event=push&status=completed" \
            | jq -r '.workflow_runs[0].id')

          echo "Workflow Run ID: $RUN_ID" > logs/aicicd_runtime.log

          # Download logs using GitHub API
          curl -s -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -o logs/aicicd_logs.zip \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs/$RUN_ID/logs"

      - name: Upload Logs
        uses: actions/upload-artifact@v4
        with:
          name: aicicd-runtime-logs
          path: logs/
