
name: Azure OpenAI Deployment

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'apply'
        type: choice
        options:
          - plan
          - apply
          - destroy
permissions:
      id-token: write
      contents: read
jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_USE_OIDC: true
      # TF_LOG: DEBUG
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.4.0'

      - name: Login to Azure
        uses: azure/login@v1
        with:
         client-id: ${{ secrets.AZURE_CLIENT_ID }}
         tenant-id: ${{ secrets.AZURE_TENANT_ID }}
         subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Initialize Terraform
        run: terraform init
        working-directory: terraform

      # - name: Force Unlock Terraform State (if locked)
      #   continue-on-error: true
      #   run: terraform force-unlock -force 3a81d085-f6e7-ec73-972c-bce2e7ae77f0
      #   working-directory: terraform

      - name: Terraform Plan
        id: plan
        if: github.event.inputs.action == 'plan'
        run: |
          terraform plan -out=tfplan -lock=false -input=false \
          -var "subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
          -var "client_id=${{ secrets.AZURE_CLIENT_ID }}" \
          -var "tenant_id=${{ secrets.AZURE_TENANT_ID }}"
        working-directory: terraform

      - name: Terraform Apply
        if: github.event.inputs.action == 'apply'
        run: |
          terraform apply -auto-approve -input=false \
          -var "subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
          -var "client_id=${{ secrets.AZURE_CLIENT_ID }}" \
          -var "tenant_id=${{ secrets.AZURE_TENANT_ID }}"
        working-directory: terraform

      - name: Terraform Destroy
        if: github.event.inputs.action == 'destroy'
        run: |
          terraform destroy -auto-approve -input=false \
          -var "subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
          -var "client_id=${{ secrets.AZURE_CLIENT_ID }}" \
          -var "tenant_id=${{ secrets.AZURE_TENANT_ID }}"
        working-directory: terraform

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install jq (for JSON parsing)
        run: sudo apt-get install -y jq

      - name: List All Runs
        run: |
          echo "Listing recent workflow runs..."
          gh run list --limit 5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: List All Jobs in the Run
        run: |
          echo "Fetching details for workflow run ID: ${{ github.run_id }}"
          gh run view ${{ github.run_id }} --json jobs | jq '.jobs[] | {id, name}'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Capture Logs
        run: |
          echo "Capturing the output of aicicd job..."
          mkdir -p logs
          
          # Get the current workflow run ID
          RUN_ID=${{ github.run_id }}

          # List all job names for debugging
          echo "Available jobs in this run:"
          gh run view $RUN_ID --json jobs | jq '.jobs[] | {id, name}'

          # Get the job ID for 'aicicd-poc'
          JOB_ID=$(gh run view $RUN_ID --json jobs | jq -r '.jobs[] | select(.name=="aicicd-poc") | .id')

          if [[ -z "$JOB_ID" || "$JOB_ID" == "null" ]]; then
            echo "Error: Could not find the job ID for 'aicicd-poc'."
            exit 1
          fi

          # Fetch logs for the specific job and save them
          gh run view $RUN_ID --job $JOB_ID --log > logs/aicicd-output.log 2>&1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Logs as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: aicicd-logs
          path: logs/aicicd-output.log
